### PR TITLE
[DEPENDENT MERGE] Return error rather than panic in Emit

### LINKED ISSUE #20: go-eventbus panics when removing StreamHandler after cancelling host context
I think this is a regression.  Removing StreamHandlers after the host context's been cancelled causes go-eventbus to panic because emmitters have been closed:

```
panic: emitter is closed

goroutine 71 [running]:
github.com/libp2p/go-eventbus.(*emitter).Emit(0xc000191200, 0xc81540, 0xc0000b7980)
	/home/kishan/code/pkg/mod/github.com/libp2p/go-eventbus@v0.0.3/basic.go:33 +0x6f
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).RemoveStreamHandler(0xc0000d62c0, 0xd4501d, 0xc)
	/home/kishan/code/pkg/mod/github.com/libp2p/go-libp2p@v0.2.1/p2p/host/basic/basic_host.go:419 +0x112
github.com/libp2p/go-libp2p-gostream.(*listener).Close(0xc000046400, 0xc00014add0, 0x10)
	/home/kishan/code/pkg/mod/github.com/libp2p/go-libp2p-gostream@v0.1.2/listener.go:39 +0x53
net/http.(*onceCloseListener).close(...)
	/usr/local/go/src/net/http/server.go:3286
sync.(*Once).Do(0xc0000b7570, 0xc00014ae00)
	/usr/local/go/src/sync/once.go:44 +0xb3
net/http.(*onceCloseListener).Close(0xc0000b7560, 0x0, 0x55)
	/usr/local/go/src/net/http/server.go:3282 +0x54
net/http.(*Server).Serve(0xc0003684e0, 0xf91f80, 0xc000046400, 0xf815e0, 0xc0000b2210)
	/usr/local/go/src/net/http/server.go:2879 +0x4b0
github.com/ipfs/ipfs-cluster/api/rest.(*API).runLibp2pServer(0xc00012b050, 0xf95700, 0xc000362980)
	/home/kishan/code/ipfs-cluster/api/rest/restapi.go:477 +0x322
created by github.com/ipfs/ipfs-cluster/api/rest.(*API).run
	/home/kishan/code/ipfs-cluster/api/rest/restapi.go:449 +0x8a
FAIL	github.com/ipfs/ipfs-cluster/api/rest	0.094s
```

### PR DESCRIPTION
**Pull request by bigs**
Hey all, this fixes #20, along with a change I'll be pushing to go-libp2p-core.

@Kubuxu & @magik6k, I think a similar overhaul should be made for `Close`, and I'm happy to make that change. Fortunately, that change wouldn't require signature change.

### CODE REVIEW

File: basic_test.go [hunk 1]
```diff
@@ -109,18 +109,13 @@ func TestEmitOnClosed(t *testing.T) {
...
-		}
-		if r.(string) != "emitter is closed" {
-			t.Error("unexpected message")
-		}
-	}()
-
-	em.Emit(EventA{})
+	err = em.Emit(EventA{})
+	if err == nil {
+		t.Errorf("expected panic")
```
Comment (magik6k) [inline basic_test.go]:
```suggestion
		t.Errorf("expected error")
```

**Review by magik6k — APPROVED** [review]
