### PR TITLE
fix panic in TestSubFailFully

### LINKED ISSUE #47: flaky tests
The panic seems to occur in a different test case (shutdown not clean?).
```
=== RUN   TestSubMany
  panic: timeout reached
  
  goroutine 32 [running]:
  github.com/libp2p/go-libp2p/p2p/host/eventbus.panicOnTimeout(0xc00005e7b8?)
  	/Users/runner/work/go-libp2p/go-libp2p/p2p/host/eventbus/basic_test.go:460 +0x38
  created by github.com/libp2p/go-libp2p/p2p/host/eventbus.TestSubFailFully
  	/Users/runner/work/go-libp2p/go-libp2p/p2p/host/eventbus/basic_test.go:475 +0x21b
  FAIL	github.com/libp2p/go-libp2p/p2p/host/eventbus	5.328s
  -test.shuffle 1660725297497886000

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #47.

### CODE REVIEW

File: basic_test.go [hunk 1]
```diff
@@ -455,11 +455,6 @@ func TestCloseBlocking(t *testing.T) {
 	sub.Close() // cancel sub
 }
 
-func panicOnTimeout(d time.Duration) {
-	<-time.After(d)
-	panic("timeout reached")
-}
```
Comment (marten-seemann) [inline basic_test.go:461]: This would _always_ panic, no matter if there was a timeout or not. The only reason this didn't show up before is that the test suite would finish before we reached the 5s timeout.

With shuffling of tests (`go test -shuffle`), this is not a valid assumption any more. Besides, `panic`king is a very bad way to end a failing test anyway.

**Review by Stebalien — APPROVED** [review]
